---

- hosts: all

  tasks:

#CPU vendor
  - name: CPU vendor | Set facts
    set_fact:
      cpu_manufacturer: "{{ ansible_facts['processor'][1] | lower | regex_replace('(authentic)|(genuine)', '') }}"
    failed_when:
      -'"amd" not in cpu_manufacturer'
      -'"intel" not in cpu_manufacturer'

  - name: IOMMU/Nouveau | Set facts
    set_fact:
      grubconfig: '{{ cpu_manufacturer }}_iommu=on iommu=pt modprobe.blacklist=nouveau'

#Configure IOMMU on KVM
  - name: Verify the GRUB defauts and modify the GRUB configuration if required
    lineinfile:
      path: /etc/default/grub
      backrefs: true
      regexp: '^(GRUB_CMDLINE_LINUX=(?!.*{{ grubconfig }})\"[^\"]+)(\")'
      line: '\1 {{ grubconfig }}\2'
    become: yes
    register: grubfile
    tags:
      - grub

#Configure VFIO kernel module
  - name: Configure and modify the VFIO configuration
    copy:
      dest: /etc/modules-load.d/vfio.conf
      content: |
        vfio
        vfio_iommu_type1
        vfio_pci
        vfio_virqfd
    become: yes
    tags:
      - vfio

#Update GRUB on the system
  - name: Register the GRUB configuraiton on UEFI/BIOS
    command: readlink -f /etc/grub2-efi.cfg
    register: EFI_GRUB_FN
    become: yes

  - name: Update the GRUB configufation on UEFI/BIOS
    command: grub2-mkconfig -o {{ EFI_GRUB_FN.stdout }}
    become: yes

#System information
  - name: Get kernel release
    command: uname -r
    register: uname_r

#Backup the current initramfs and build new one
  - name: Backup the current intiramfs
    command: mv /boot/initramfs-{{ uname_r.stdout }}.img /boot/initramfs-{{ uname_r.stdout }}.nouveau.img
    become: yes
    tags:
      - intiramfs

  - name: Rebuild the new initramfs
    command: dracut /boot/initramfs-{{ uname_r.stdout }}.img {{ uname_r.stdout }}
    become: yes
    tags:
      - dracut

#Reboot
  - name: Reboot the target server immediately if there was a change
    shell: "sleep 5 && reboot"
    async: 1
    poll: 0
    when: grubfile is changed

  - name: Wait for the reboot to complete if there was a change
    wait_for_connection:
      connect_timeout: 20
      sleep: 5
      delay: 5
      timeout: 300
    when: grubfile is changed

#Perform the testing
  - name: Confirm the IOMMU groups has been corretly enabled
    command: cat /proc/cmdline
    register: iommu
    failed_when:
      - '"iommu=on" not in iommu.stdout'

  - name: Confirm the VFIO has loaded and bound to the right devices
    shell: lsmod | grep vfio
    register: vfio
    failed_when:
      - '"vfio" not in vfio.stdout'